// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2025 Effortless Metrics, Inc.
// Auto-generated; do not edit.
// Generated by scripts/gen-build-info.sh on Wed Feb 25 06:39:12 EST 2026
public enum BuildInfo {
  public static let version = "v1.0.0"
  public static let git = "bd14696"
  public static let builtAt = "2026-02-25T11:39:12Z"
  public static let schemaVersion = "1.0.0"
}
