// Auto-generated; do not edit.
// Generated by scripts/gen-build-info.sh on Sun Sep  7 14:14:35 EDT 2025
public enum BuildInfo {
  public static let version = "v1.0.1"
  public static let git = "bc4f3a1"
  public static let builtAt = "2025-09-07T18:14:35Z"
  public static let schemaVersion = "1.0.0"
}
