// Auto-generated; do not edit.
// Generated by scripts/gen-build-info.sh on Wed Sep 17 22:36:57 EDT 2025
public enum BuildInfo {
  public static let version = "v1.0.2"
  public static let git = "6bf0ecc"
  public static let builtAt = "2025-09-18T02:36:57Z"
  public static let schemaVersion = "1.0.0"
}
