// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2025 Effortless Metrics, Inc.

import Foundation
import XCTest

@testable import SwiftMTPObservability

// MARK: - Log Level Filtering Tests

final class Wave29LogLevelFilteringTests: XCTestCase {

  func testFiveCategoryLoggersExist() {
    // Verify all five category loggers are accessible without crash.
    let loggers = [MTPLog.transport, MTPLog.proto, MTPLog.index, MTPLog.sync, MTPLog.perf]
    XCTAssertEqual(loggers.count, 5)
  }

  func testSignpostLoggersAreAccessible() {
    // Four signpost loggers should all be accessible.
    _ = MTPLog.Signpost.enumerate
    _ = MTPLog.Signpost.transfer
    _ = MTPLog.Signpost.resume
    _ = MTPLog.Signpost.chunk
  }

  func testSignpostSignpostersAreAccessible() {
    // Four signposters should all be accessible.
    _ = MTPLog.Signpost.enumerateSignposter
    _ = MTPLog.Signpost.transferSignposter
    _ = MTPLog.Signpost.resumeSignposter
    _ = MTPLog.Signpost.chunkSignposter
  }

  func testSubsystemIsStableAcrossAccesses() {
    let s1 = MTPLog.subsystem
    let s2 = MTPLog.subsystem
    XCTAssertEqual(s1, s2)
    XCTAssertEqual(s1, "com.effortlessmetrics.swiftmtp")
  }

  func testAllOutcomeClassesCanServeAsLogLevelProxy() {
    // TransactionOutcome acts as severity for transaction logs.
    let severity: [TransactionOutcome: Int] = [
      .ok: 0, .cancelled: 1, .stall: 2, .timeout: 3, .ioError: 4, .deviceError: 5,
    ]
    XCTAssertEqual(severity.count, 6)
    XCTAssertLessThan(severity[.ok]!, severity[.deviceError]!)
  }
}

// MARK: - Structured Log Metadata Propagation Tests

final class Wave29StructuredMetadataPropagationTests: XCTestCase {

  private func makeRecord(
    txID: UInt32 = 1, opcode: UInt16 = 0x1009, sessionID: UInt32 = 1,
    bytesIn: Int = 256, bytesOut: Int = 0, duration: TimeInterval = 0.1,
    outcome: TransactionOutcome = .ok, errorDescription: String? = nil
  ) -> TransactionRecord {
    TransactionRecord(
      txID: txID, opcode: opcode,
      opcodeLabel: MTPOpcodeLabel.label(for: opcode),
      sessionID: sessionID, startedAt: Date(timeIntervalSince1970: 1_700_000_000),
      duration: duration, bytesIn: bytesIn, bytesOut: bytesOut,
      outcomeClass: outcome, errorDescription: errorDescription)
  }

  func testMetadataPropagatesThroughAppendAndRecent() async {
    let log = TransactionLog()
    let original = makeRecord(txID: 77, opcode: 0x100D, sessionID: 9, bytesOut: 4096, duration: 2.5)
    await log.append(original)
    let retrieved = await log.recent(limit: 1)
    XCTAssertEqual(retrieved.count, 1)
    let r = retrieved[0]
    XCTAssertEqual(r.txID, 77)
    XCTAssertEqual(r.opcode, 0x100D)
    XCTAssertEqual(r.opcodeLabel, "SendObject")
    XCTAssertEqual(r.sessionID, 9)
    XCTAssertEqual(r.bytesOut, 4096)
    XCTAssertEqual(r.duration, 2.5, accuracy: 0.001)
  }

  func testMetadataPropagatesThroughJSONDumpRoundTrip() async throws {
    let log = TransactionLog()
    let original = makeRecord(
      txID: 42, opcode: 0x1008, sessionID: 3,
      bytesIn: 8192, duration: 0.75, outcome: .timeout,
      errorDescription: "timed out")
    await log.append(original)
    let json = await log.dump(redacting: false)
    let data = json.data(using: .utf8)!
    let decoder = JSONDecoder()
    decoder.dateDecodingStrategy = .iso8601
    let records = try decoder.decode([TransactionRecord].self, from: data)
    let r = try XCTUnwrap(records.first)
    XCTAssertEqual(r.txID, 42)
    XCTAssertEqual(r.opcode, 0x1008)
    XCTAssertEqual(r.opcodeLabel, "GetObjectInfo")
    XCTAssertEqual(r.sessionID, 3)
    XCTAssertEqual(r.bytesIn, 8192)
    XCTAssertEqual(r.outcomeClass, .timeout)
    XCTAssertEqual(r.errorDescription, "timed out")
  }

  func testOpcodeLabelAutoGeneratedFromOpcode() {
    let r = makeRecord(opcode: 0x1004)
    XCTAssertEqual(r.opcodeLabel, "GetStorageIDs")
  }

  func testOpcodeLabelUnknownAutoGenerated() {
    let r = makeRecord(opcode: 0xABCD)
    XCTAssertEqual(r.opcodeLabel, "Unknown(0xABCD)")
  }
}

// MARK: - Performance Metric Collection During Concurrent Operations

final class Wave29ConcurrentMetricCollectionTests: XCTestCase {

  func testConcurrentAppendsThenAggregateByteCounters() async {
    let log = TransactionLog()
    let count: UInt32 = 200
    await withTaskGroup(of: Void.self) { group in
      for i: UInt32 in 1...count {
        group.addTask {
          let record = TransactionRecord(
            txID: i, opcode: 0x1009, opcodeLabel: "GetObject",
            sessionID: 1, startedAt: Date(), duration: 0.01,
            bytesIn: 100, bytesOut: 50, outcomeClass: .ok)
          await log.append(record)
        }
      }
    }
    let all = await log.recent(limit: Int(count) + 10)
    XCTAssertEqual(all.count, Int(count))
    let totalBytesIn = all.reduce(0) { $0 + $1.bytesIn }
    let totalBytesOut = all.reduce(0) { $0 + $1.bytesOut }
    XCTAssertEqual(totalBytesIn, Int(count) * 100)
    XCTAssertEqual(totalBytesOut, Int(count) * 50)
  }

  func testConcurrentAppendsThenAggregateDurations() async {
    let log = TransactionLog()
    let count: UInt32 = 150
    await withTaskGroup(of: Void.self) { group in
      for i: UInt32 in 1...count {
        group.addTask {
          let record = TransactionRecord(
            txID: i, opcode: 0x1002, opcodeLabel: "OpenSession",
            sessionID: 1, startedAt: Date(), duration: 0.25,
            bytesIn: 0, bytesOut: 0, outcomeClass: .ok)
          await log.append(record)
        }
      }
    }
    let all = await log.recent(limit: 200)
    let totalDuration = all.reduce(0.0) { $0 + $1.duration }
    XCTAssertEqual(totalDuration, Double(count) * 0.25, accuracy: 0.001)
  }

  func testConcurrentEWMAUpdatesOnSeparateInstances() async {
    // Each task gets its own EWMA — verify no cross-contamination.
    let results = await withTaskGroup(of: Double.self, returning: [Double].self) { group in
      for rate in [1000.0, 2000.0, 5000.0, 10000.0] {
        group.addTask {
          var ewma = ThroughputEWMA()
          for _ in 0..<50 {
            ewma.update(bytes: Int(rate), dt: 1.0)
          }
          return ewma.bytesPerSecond
        }
      }
      var collected: [Double] = []
      for await value in group { collected.append(value) }
      return collected
    }
    XCTAssertEqual(results.count, 4)
    let sorted = results.sorted()
    XCTAssertEqual(sorted[0], 1000.0, accuracy: 1.0)
    XCTAssertEqual(sorted[1], 2000.0, accuracy: 1.0)
    XCTAssertEqual(sorted[2], 5000.0, accuracy: 1.0)
    XCTAssertEqual(sorted[3], 10000.0, accuracy: 1.0)
  }

  func testConcurrentRingBufferCollectionOnSeparateInstances() async {
    let results = await withTaskGroup(of: Double.self, returning: [Double].self) { group in
      for baseVal in [10.0, 100.0, 1000.0] {
        group.addTask {
          var buf = ThroughputRingBuffer(maxSamples: 50)
          for i in 0..<50 { buf.addSample(baseVal + Double(i)) }
          return buf.average ?? 0
        }
      }
      var collected: [Double] = []
      for await v in group { collected.append(v) }
      return collected
    }
    XCTAssertEqual(results.count, 3)
    let sorted = results.sorted()
    // Averages: 10+24.5=34.5, 100+24.5=124.5, 1000+24.5=1024.5
    XCTAssertEqual(sorted[0], 34.5, accuracy: 0.1)
    XCTAssertEqual(sorted[1], 124.5, accuracy: 0.1)
    XCTAssertEqual(sorted[2], 1024.5, accuracy: 0.1)
  }
}

// MARK: - Log Sink Configuration and Output Format Validation

final class Wave29LogSinkFormatTests: XCTestCase {

  private func makeRecord(txID: UInt32, errorDescription: String? = nil) -> TransactionRecord {
    TransactionRecord(
      txID: txID, opcode: 0x1009, opcodeLabel: "GetObject",
      sessionID: 1, startedAt: Date(timeIntervalSince1970: 1_700_000_000),
      duration: 0.5, bytesIn: 1024, bytesOut: 0,
      outcomeClass: .ok, errorDescription: errorDescription)
  }

  func testDumpOutputIsValidUTF8() async {
    let log = TransactionLog()
    await log.append(makeRecord(txID: 1))
    let json = await log.dump(redacting: false)
    XCTAssertNotNil(json.data(using: .utf8))
  }

  func testDumpOutputIsDecodableBackToRecords() async throws {
    let log = TransactionLog()
    for i: UInt32 in 1...3 { await log.append(makeRecord(txID: i)) }
    let json = await log.dump(redacting: false)
    let data = json.data(using: .utf8)!
    let decoder = JSONDecoder()
    decoder.dateDecodingStrategy = .iso8601
    let records = try decoder.decode([TransactionRecord].self, from: data)
    XCTAssertEqual(records.count, 3)
    XCTAssertEqual(records.map(\.txID), [1, 2, 3])
  }

  func testDumpSortedKeysOrder() async {
    let log = TransactionLog()
    await log.append(makeRecord(txID: 1, errorDescription: "err"))
    let json = await log.dump(redacting: false)
    // With sortedKeys: bytesIn < bytesOut < duration < errorDescription < opcode < ...
    let keys = ["bytesIn", "bytesOut", "duration", "errorDescription", "opcode",
                "opcodeLabel", "outcomeClass", "sessionID", "startedAt", "txID"]
    var lastIndex = json.startIndex
    for key in keys {
      if let range = json.range(of: "\"\(key)\"") {
        XCTAssertGreaterThanOrEqual(range.lowerBound, lastIndex, "Key \(key) out of sorted order")
        lastIndex = range.lowerBound
      }
    }
  }

  func testDumpRedactedOutputIsAlsoDecodable() async throws {
    let log = TransactionLog()
    await log.append(makeRecord(txID: 1, errorDescription: "serial=AABBCCDDEE112233"))
    let json = await log.dump(redacting: true)
    let data = json.data(using: .utf8)!
    let decoder = JSONDecoder()
    decoder.dateDecodingStrategy = .iso8601
    let records = try decoder.decode([TransactionRecord].self, from: data)
    XCTAssertEqual(records.count, 1)
    XCTAssertTrue(records[0].errorDescription?.contains("<redacted>") ?? false)
  }
}

// MARK: - Memory-Bounded Log Buffer Behavior

final class Wave29MemoryBoundedBufferTests: XCTestCase {

  private func makeRecord(txID: UInt32) -> TransactionRecord {
    TransactionRecord(
      txID: txID, opcode: 0x1001, opcodeLabel: "GetDeviceInfo",
      sessionID: 1, startedAt: Date(), duration: 0.01,
      bytesIn: 8, bytesOut: 0, outcomeClass: .ok)
  }

  func testExactlyAtMaxRecordsBoundary() async {
    let log = TransactionLog()
    for i: UInt32 in 1...1000 {
      await log.append(makeRecord(txID: i))
    }
    let all = await log.recent(limit: 2000)
    XCTAssertEqual(all.count, 1000)
    XCTAssertEqual(all.first?.txID, 1)
    XCTAssertEqual(all.last?.txID, 1000)
  }

  func testOneOverMaxRecordsBoundary() async {
    let log = TransactionLog()
    for i: UInt32 in 1...1001 {
      await log.append(makeRecord(txID: i))
    }
    let all = await log.recent(limit: 2000)
    XCTAssertEqual(all.count, 1000)
    XCTAssertEqual(all.first?.txID, 2)
    XCTAssertEqual(all.last?.txID, 1001)
  }

  func testOneUnderMaxRecordsBoundary() async {
    let log = TransactionLog()
    for i: UInt32 in 1...999 {
      await log.append(makeRecord(txID: i))
    }
    let all = await log.recent(limit: 2000)
    XCTAssertEqual(all.count, 999)
    XCTAssertEqual(all.first?.txID, 1)
  }

  func testDoubleMaxRecordsEvictsFirstHalf() async {
    let log = TransactionLog()
    for i: UInt32 in 1...2000 {
      await log.append(makeRecord(txID: i))
    }
    let all = await log.recent(limit: 3000)
    XCTAssertEqual(all.count, 1000)
    XCTAssertEqual(all.first?.txID, 1001)
    XCTAssertEqual(all.last?.txID, 2000)
  }

  func testRingBufferExactlyAtCapacity() {
    var buf = ThroughputRingBuffer(maxSamples: 5)
    for i in 1...5 { buf.addSample(Double(i)) }
    XCTAssertEqual(buf.count, 5)
    XCTAssertEqual(buf.allSamples.sorted(), [1, 2, 3, 4, 5])
  }

  func testRingBufferOneOverCapacity() {
    var buf = ThroughputRingBuffer(maxSamples: 5)
    for i in 1...6 { buf.addSample(Double(i)) }
    XCTAssertEqual(buf.count, 5)
    XCTAssertFalse(buf.allSamples.contains(1.0))
    XCTAssertTrue(buf.allSamples.contains(6.0))
  }

  func testRingBufferMultipleFullRotations() {
    var buf = ThroughputRingBuffer(maxSamples: 3)
    for i in 1...30 { buf.addSample(Double(i)) }
    XCTAssertEqual(buf.count, 3)
    XCTAssertEqual(buf.allSamples.sorted(), [28, 29, 30])
  }

  func testClearThenRefillToCapacity() async {
    let log = TransactionLog()
    for i: UInt32 in 1...1000 { await log.append(makeRecord(txID: i)) }
    await log.clear()
    for i: UInt32 in 2001...3000 { await log.append(makeRecord(txID: i)) }
    let all = await log.recent(limit: 2000)
    XCTAssertEqual(all.count, 1000)
    XCTAssertEqual(all.first?.txID, 2001)
    XCTAssertEqual(all.last?.txID, 3000)
  }
}

// MARK: - Correlation ID Tracking Across Async Operations

final class Wave29CorrelationIDTrackingTests: XCTestCase {

  func testCorrelationIDPreservedAcrossAsyncBoundary() async {
    let log = TransactionLog()
    let record = TransactionRecord(
      txID: 55555, opcode: 0x1009, opcodeLabel: "GetObject",
      sessionID: 88, startedAt: Date(), duration: 0.1,
      bytesIn: 256, bytesOut: 0, outcomeClass: .ok)

    await Task { await log.append(record) }.value
    let retrieved = await Task { await log.recent(limit: 1) }.value
    XCTAssertEqual(retrieved.first?.txID, 55555)
    XCTAssertEqual(retrieved.first?.sessionID, 88)
  }

  func testSessionIDGroupingAcrossConcurrentAppends() async {
    let log = TransactionLog()
    await withTaskGroup(of: Void.self) { group in
      for i: UInt32 in 1...50 {
        group.addTask {
          let record = TransactionRecord(
            txID: i, opcode: 0x1009, opcodeLabel: "GetObject",
            sessionID: i % 3 + 1, startedAt: Date(), duration: 0.01,
            bytesIn: 64, bytesOut: 0, outcomeClass: .ok)
          await log.append(record)
        }
      }
    }
    let all = await log.recent(limit: 60)
    XCTAssertEqual(all.count, 50)
    let grouped = Dictionary(grouping: all, by: \.sessionID)
    // Sessions 1, 2, 3; distribution: 17, 17, 16 (or similar)
    XCTAssertEqual(grouped.keys.count, 3)
    for (_, records) in grouped {
      XCTAssertGreaterThan(records.count, 10)
    }
  }

  func testTxIDUniquenessAcrossConcurrentAppends() async {
    let log = TransactionLog()
    let count: UInt32 = 300
    await withTaskGroup(of: Void.self) { group in
      for i: UInt32 in 1...count {
        group.addTask {
          let record = TransactionRecord(
            txID: i, opcode: 0x1001, opcodeLabel: "GetDeviceInfo",
            sessionID: 1, startedAt: Date(), duration: 0.01,
            bytesIn: 0, bytesOut: 0, outcomeClass: .ok)
          await log.append(record)
        }
      }
    }
    let all = await log.recent(limit: Int(count) + 10)
    let ids = Set(all.map(\.txID))
    XCTAssertEqual(ids.count, Int(count))
  }

  func testCorrelationIDSurvivesDumpAndDecode() async throws {
    let log = TransactionLog()
    let record = TransactionRecord(
      txID: 999_888, opcode: 0x1009, opcodeLabel: "GetObject",
      sessionID: 777, startedAt: Date(timeIntervalSince1970: 1_700_000_000),
      duration: 0.1, bytesIn: 512, bytesOut: 0, outcomeClass: .ok)
    await log.append(record)
    let json = await log.dump(redacting: false)
    let data = json.data(using: .utf8)!
    let decoder = JSONDecoder()
    decoder.dateDecodingStrategy = .iso8601
    let records = try decoder.decode([TransactionRecord].self, from: data)
    XCTAssertEqual(records.first?.txID, 999_888)
    XCTAssertEqual(records.first?.sessionID, 777)
  }
}

// MARK: - Performance Regression Detection Thresholds

final class Wave29PerformanceRegressionThresholdTests: XCTestCase {

  func testDetectRegressionAboveThreshold() {
    var ewma = ThroughputEWMA()
    let baseline = 10_000_000.0
    // Simulate 50% regression
    for _ in 0..<50 { ewma.update(bytes: 5_000_000, dt: 1.0) }
    let regressionPct = (baseline - ewma.bytesPerSecond) / baseline * 100
    XCTAssertGreaterThan(regressionPct, 45.0)
  }

  func testNoRegressionWithinTolerance() {
    var ewma = ThroughputEWMA()
    let baseline = 10_000_000.0
    let tolerance = 5.0 // 5%
    // Simulate very close to baseline
    for _ in 0..<50 { ewma.update(bytes: 9_800_000, dt: 1.0) }
    let deviationPct = abs(baseline - ewma.bytesPerSecond) / baseline * 100
    XCTAssertLessThan(deviationPct, tolerance)
  }

  func testDetectImprovementAboveThreshold() {
    var ewma = ThroughputEWMA()
    let baseline = 5_000_000.0
    for _ in 0..<50 { ewma.update(bytes: 10_000_000, dt: 1.0) }
    let improvementPct = (ewma.bytesPerSecond - baseline) / baseline * 100
    XCTAssertGreaterThan(improvementPct, 90.0)
  }

  func testP95RegressionDetectionViaRingBuffer() {
    let baseline_p95 = 50.0
    var buf = ThroughputRingBuffer(maxSamples: 200)
    // Simulate slower p95
    for _ in 0..<95 { buf.addSample(30.0) }
    for _ in 0..<5 { buf.addSample(200.0) } // tail latency spike
    let current_p95 = buf.p95!
    XCTAssertGreaterThan(current_p95, baseline_p95)
  }

  func testStablePerformanceNoFalseRegressionAlarm() {
    var ewma = ThroughputEWMA()
    let baseline = 8_000_000.0
    let threshold = 10.0 // 10%
    // Feed stable rate
    for _ in 0..<100 { ewma.update(bytes: 8_000_000, dt: 1.0) }
    let deviationPct = abs(ewma.bytesPerSecond - baseline) / baseline * 100
    XCTAssertLessThan(deviationPct, threshold)
  }

  func testRegressionDetectedAfterGradualSlowdown() {
    var ewma = ThroughputEWMA()
    // Establish fast baseline
    for _ in 0..<30 { ewma.update(bytes: 10_000_000, dt: 1.0) }
    let fast = ewma.bytesPerSecond
    // Gradually slow down
    for _ in 0..<30 { ewma.update(bytes: 3_000_000, dt: 1.0) }
    let slow = ewma.bytesPerSecond
    XCTAssertLessThan(slow, fast * 0.5)
  }
}

// MARK: - Log Sanitization (No PII in Device Info Logs)

final class Wave29LogSanitizationTests: XCTestCase {

  private func makeRecord(errorDescription: String?) -> TransactionRecord {
    TransactionRecord(
      txID: 1, opcode: 0x1001, opcodeLabel: "GetDeviceInfo",
      sessionID: 1, startedAt: Date(), duration: 0.1,
      bytesIn: 0, bytesOut: 0, outcomeClass: .deviceError,
      errorDescription: errorDescription)
  }

  func testRedactsLongHexSerialNumber() async {
    let log = TransactionLog()
    await log.append(makeRecord(errorDescription: "SN=0123456789ABCDEF01234567"))
    let json = await log.dump(redacting: true)
    XCTAssertFalse(json.contains("0123456789ABCDEF01234567"))
    XCTAssertTrue(json.contains("<redacted>"))
  }

  func testRedactsMACAddressLikeHex() async {
    let log = TransactionLog()
    // MAC without colons appears as 12-char hex string, above 8-char threshold
    await log.append(makeRecord(errorDescription: "mac=AABBCCDDEEFF"))
    let json = await log.dump(redacting: true)
    XCTAssertFalse(json.contains("AABBCCDDEEFF"))
    XCTAssertTrue(json.contains("<redacted>"))
  }

  func testPreservesShortOpcodeLikeHex() async {
    let log = TransactionLog()
    await log.append(makeRecord(errorDescription: "opcode 0x100D returned error"))
    let json = await log.dump(redacting: true)
    // "100D" is only 4 hex chars — should NOT be redacted
    XCTAssertTrue(json.contains("100D"))
  }

  func testRedactsMultipleHexTokensInSameMessage() async {
    let log = TransactionLog()
    await log.append(
      makeRecord(errorDescription: "devA=1122334455667788 devB=AABBCCDDEEFF0011"))
    let json = await log.dump(redacting: true)
    XCTAssertFalse(json.contains("1122334455667788"))
    XCTAssertFalse(json.contains("AABBCCDDEEFF0011"))
    // Non-hex text preserved
    XCTAssertTrue(json.contains("devA"))
    XCTAssertTrue(json.contains("devB"))
  }

  func testNonHexDeviceInfoPreserved() async {
    let log = TransactionLog()
    await log.append(
      makeRecord(errorDescription: "Device: Pixel 7 on USB bus 3, port 2"))
    let json = await log.dump(redacting: true)
    XCTAssertTrue(json.contains("Pixel 7"))
    XCTAssertTrue(json.contains("USB bus 3"))
  }

  func testRedactionIdempotent() async {
    let log = TransactionLog()
    await log.append(makeRecord(errorDescription: "id=AABBCCDD11223344"))
    let json1 = await log.dump(redacting: true)
    // Dump again — same result (no double-redaction issue since dump reads from original)
    let json2 = await log.dump(redacting: true)
    XCTAssertEqual(json1, json2)
  }

  func testRedactionDoesNotAlterRecordsWithNilError() async {
    let log = TransactionLog()
    await log.append(makeRecord(errorDescription: nil))
    let redacted = await log.dump(redacting: true)
    let data = redacted.data(using: .utf8)!
    let arr = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]]
    XCTAssertEqual(arr?.count, 1)
  }

  func testExactly8HexCharsRedacted() async {
    let log = TransactionLog()
    await log.append(makeRecord(errorDescription: "code=AABBCCDD"))
    let json = await log.dump(redacting: true)
    XCTAssertTrue(json.contains("<redacted>"))
    XCTAssertFalse(json.contains("AABBCCDD"))
  }

  func testExactly7HexCharsNotRedacted() async {
    let log = TransactionLog()
    await log.append(makeRecord(errorDescription: "code=AABBCCD"))
    let json = await log.dump(redacting: true)
    XCTAssertTrue(json.contains("AABBCCD"))
  }
}

// MARK: - Metric Aggregation Accuracy (Counts, Durations, Byte Totals)

final class Wave29MetricAggregationAccuracyTests: XCTestCase {

  private func makeRecord(
    txID: UInt32, bytesIn: Int = 0, bytesOut: Int = 0,
    duration: TimeInterval = 0.1, outcome: TransactionOutcome = .ok
  ) -> TransactionRecord {
    TransactionRecord(
      txID: txID, opcode: 0x1009, opcodeLabel: "GetObject",
      sessionID: 1, startedAt: Date(), duration: duration,
      bytesIn: bytesIn, bytesOut: bytesOut, outcomeClass: outcome)
  }

  func testTotalBytesInAggregation() async {
    let log = TransactionLog()
    for i: UInt32 in 1...10 {
      await log.append(makeRecord(txID: i, bytesIn: 1024))
    }
    let all = await log.recent(limit: 20)
    let total = all.reduce(0) { $0 + $1.bytesIn }
    XCTAssertEqual(total, 10 * 1024)
  }

  func testTotalBytesOutAggregation() async {
    let log = TransactionLog()
    for i: UInt32 in 1...8 {
      await log.append(makeRecord(txID: i, bytesOut: 2048))
    }
    let all = await log.recent(limit: 20)
    let total = all.reduce(0) { $0 + $1.bytesOut }
    XCTAssertEqual(total, 8 * 2048)
  }

  func testTotalDurationAggregation() async {
    let log = TransactionLog()
    for i: UInt32 in 1...5 {
      await log.append(makeRecord(txID: i, duration: 0.5))
    }
    let all = await log.recent(limit: 10)
    let totalDuration = all.reduce(0.0) { $0 + $1.duration }
    XCTAssertEqual(totalDuration, 2.5, accuracy: 0.001)
  }

  func testErrorCountAggregation() async {
    let log = TransactionLog()
    await log.append(makeRecord(txID: 1, outcome: .ok))
    await log.append(makeRecord(txID: 2, outcome: .timeout))
    await log.append(makeRecord(txID: 3, outcome: .ok))
    await log.append(makeRecord(txID: 4, outcome: .stall))
    await log.append(makeRecord(txID: 5, outcome: .ok))
    await log.append(makeRecord(txID: 6, outcome: .ioError))
    let all = await log.recent(limit: 10)
    let okCount = all.filter { $0.outcomeClass == .ok }.count
    let errorCount = all.filter { $0.outcomeClass != .ok }.count
    XCTAssertEqual(okCount, 3)
    XCTAssertEqual(errorCount, 3)
  }

  func testMixedByteCountAggregation() async {
    let log = TransactionLog()
    await log.append(makeRecord(txID: 1, bytesIn: 100, bytesOut: 0))
    await log.append(makeRecord(txID: 2, bytesIn: 0, bytesOut: 200))
    await log.append(makeRecord(txID: 3, bytesIn: 300, bytesOut: 400))
    let all = await log.recent(limit: 10)
    let totalIn = all.reduce(0) { $0 + $1.bytesIn }
    let totalOut = all.reduce(0) { $0 + $1.bytesOut }
    XCTAssertEqual(totalIn, 400)
    XCTAssertEqual(totalOut, 600)
  }

  func testAverageDurationComputation() async {
    let log = TransactionLog()
    let durations: [TimeInterval] = [0.1, 0.2, 0.3, 0.4, 0.5]
    for (i, d) in durations.enumerated() {
      await log.append(makeRecord(txID: UInt32(i + 1), duration: d))
    }
    let all = await log.recent(limit: 10)
    let avg = all.reduce(0.0) { $0 + $1.duration } / Double(all.count)
    XCTAssertEqual(avg, 0.3, accuracy: 0.001)
  }

  func testEWMAAccuracyAfterManyUpdates() {
    var ewma = ThroughputEWMA()
    // Feed exactly 1 MB/s for 500 samples
    let mb = 1024 * 1024
    for _ in 0..<500 {
      ewma.update(bytes: mb, dt: 1.0)
    }
    XCTAssertEqual(ewma.megabytesPerSecond, 1.0, accuracy: 0.0001)
  }

  func testRingBufferAverageAccuracyWithLargeDataset() {
    var buf = ThroughputRingBuffer(maxSamples: 1000)
    var expectedSum = 0.0
    for i in 1...1000 {
      let v = Double(i)
      buf.addSample(v)
      expectedSum += v
    }
    let expectedAvg = expectedSum / 1000.0
    XCTAssertEqual(buf.average!, expectedAvg, accuracy: 0.001)
  }

  func testOutcomeBreakdownGrouping() async {
    let log = TransactionLog()
    let outcomes: [(UInt32, TransactionOutcome)] = [
      (1, .ok), (2, .ok), (3, .timeout), (4, .timeout), (5, .timeout),
      (6, .stall), (7, .ioError), (8, .deviceError), (9, .cancelled), (10, .ok),
    ]
    for (id, outcome) in outcomes {
      await log.append(makeRecord(txID: id, outcome: outcome))
    }
    let all = await log.recent(limit: 20)
    let grouped = Dictionary(grouping: all, by: \.outcomeClass)
    XCTAssertEqual(grouped[.ok]?.count, 3)
    XCTAssertEqual(grouped[.timeout]?.count, 3)
    XCTAssertEqual(grouped[.stall]?.count, 1)
    XCTAssertEqual(grouped[.ioError]?.count, 1)
    XCTAssertEqual(grouped[.deviceError]?.count, 1)
    XCTAssertEqual(grouped[.cancelled]?.count, 1)
  }
}
