#!/usr/bin/env bash
set -euo pipefail

# Generate build info for SwiftMTP
# Usage: scripts/gen-build-info.sh <output-path>

OUT="${1:?path to BuildInfo.swift}"

# Get version info
TAG="$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0-dev")"
SHA="$(git rev-parse --short HEAD)"
DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
SCHEMA="1.0.0"  # keep in sync with quirks/submission schema

# Generate Swift file
cat >"$OUT" <<EOF
// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2025 Effortless Metrics, Inc.
// Auto-generated; do not edit.
// Generated by scripts/gen-build-info.sh on $(date)
public enum BuildInfo {
  public static let version = "$TAG"
  public static let git = "$SHA"
  public static let builtAt = "$DATE"
  public static let schemaVersion = "$SCHEMA"
}
EOF

echo "Generated BuildInfo.swift at $OUT"
echo "  Version: $TAG"
echo "  Git SHA: $SHA"
echo "  Built at: $DATE"
echo "  Schema: $SCHEMA"
